// Code generated by "stringer -type=KILL ./hello.go"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[K1-0]
	_ = x[K2-1]
	_ = x[K3-2]
	_ = x[K4-3]
	_ = x[K5-4]
	_ = x[K6-5]
	_ = x[K7-6]
	_ = x[K8-7]
	_ = x[K9-8]
	_ = x[K10-9]
	_ = x[K11-10]
}

const _KILL_name = "K1K2K3K4K5K6K7K8K9K10K11"

var _KILL_index = [...]uint8{0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 21, 24}

func (i KILL) String() string {
	if i < 0 || i >= KILL(len(_KILL_index)-1) {
		return "KILL(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _KILL_name[_KILL_index[i]:_KILL_index[i+1]]
}
